variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PYTHONDEVMODE: "1"
    RUNNER_GENERATE_ARTIFACTS_METADATA: "true"
    SLSA_PROVENANCE_SCHEMA_VERSION: "v1"

cache:
    paths:
        - ".cache/pip"

default:
    image: "docker.io/python:3"

build:
    stage: "build"
    script:
        - "pip install build"
        - "python3 -m build ."
    artifacts:
        paths:
            - "dist/*"
        expire_in: "1 week"

install:
    stage: "test"
    script:
        - "pip install dist/*.whl"

check build:
    stage: "test"
    script:
        - "pip install twine"
        - "twine check dist/*"

lint:
    stage: "test"
    script:
        - "pip install flake8"
        - "flake8 ."

test:
    stage: "test"
    script:
        - "pip install hatch"
        - "hatch test"
